# Generated by Django 5.0 on 2024-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_transmission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gps_service',
            field=models.BooleanField(default=False),
        ),
    ]
