# Generated by Django 5.0 on 2023-12-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
