# Generated by Django 5.0 on 2024-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsManagement', '0002_car_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images'),
        ),
    ]
